### PR TITLE
HACS support

### PR DESCRIPTION
**Pull request by brianhanifin**
I have added HACS support to the repository. I haven't made any changes to any files besides the readme.md. Except for moving the python files to a new folder `/custom_components/smarthinq`. 

hacs-smartthinq-integration

Unfortunately I can't seem to get wideq to list my new washing machine. But that's no reason not to give this repo HACS support. :)

### CODE REVIEW

**Comment by brianhanifin** [comment]
This resolves #31.

**Comment by sampsyo** [comment]
Nice; thank you for diving into this!! Just to clarify, does HACS require that there be a top-level `custom_components` wrapper for the module? If so, that's fine, but if not, it would be slightly nicer (for the non-HACS `git clone` installation mode) to not add that. For example, these instructions from the README will no longer work:

```
$ cd custom_components
$ git clone https://github.com/sampsyo/hass-smartthinq.git smartthinq
```

…and I'll have to change my server's setup before I next `git pull` the latest version there. :smiley:

**Comment by brianhanifin** [comment]
I followed the [custom components blueprint](https://github.com/custom-components/blueprint). But I just found [documentation on hacs.json](https://hacs.xyz/docs/publish/start#hacsjson), for `content_in_root` property. I'm going to do a quick experiment to see if I can move the files back to the root for you.

**Comment by mshrem** [comment]
Hey guys thank you for this.... 

I am trying to add the repo into the HACS store but nothing happens. 
Is this still ongoing ??
Can i help in any way to get this to work?

**Comment by brianhanifin** [comment]
I closed this pull request because @sampsyo requested a change, and I wanted to submit the change cleanly. Custom HACS support is implemented by pull request #36, which is awaiting for @sampsyo to merge into his repository.

**Comment by simbus82** [comment]
I'm waiting this too! The "manual" method is not working in RPi4 with Home Assistant with HACS

**Pull request closed without merging**
