### PR TITLE
Add combined validation

### LINKED ISSUE #88: Do you want me to add GitHub Actions?
If you want, I can contribute some advanced CI to your repository in a PR. Let me know if you want that.

### PR DESCRIPTION
**Pull request by KTibow**
This adds some GitHub Actions with Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python). Closes #88.

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks! Maybe I'm being dense here, but I thought because you put `pull_request:` under the `on:` section, this would run the action so we could see what it does on the pull request here. Do you know why it wasn't triggered?

(To clarify why this is important: if we're going to merge a flake8 check, we should probably make the code pass that check.)

**Comment by KTibow** [comment]
It's odd that that didn't happen. You will need to add a topic, such as `home-assistant`, for the HACS check to pass. I'll try to bump it.

**Comment by KTibow** [comment]
Looks like hassfest is unhappy. I'll try to fix this.
https://github.com/KTibow/hass-smartthinq/runs/1404229065
```

Hassfest
  Validating json... done in 0.00s
  Validating codeowners... done in 0.00s
  Validating config_flow... done in 0.00s
  Validating dependencies... done in 0.01s
  Validating manifest... done in 0.00s
  Validating mqtt... done in 0.00s
  Validating services... done in 0.00s
  Validating ssdp... done in 0.00s
  Validating translations... done in 0.00s
  Validating zeroconf... done in 0.00s
  
  Integrations: 1
  Invalid integrations: 1
  
  Integration  - .:
  * [MANIFEST] Domain does not match dir name
```

**Comment by KTibow** [comment]
Sorry, forgot to disable formatting. Give me a sec...

**Comment by KTibow** [comment]
Sorry for the inconvenience, I fixed it and it's ready. You can view the actions [if you want](https://github.com/KTibow/hass-smartthinq/actions).

**Pull request closed without merging**
