### PR TITLE
HACS Support

### PR DESCRIPTION
**Pull request by brianhanifin**
I started over and am submitting the repository in a cleaner form. The only files I touched are: README.md, hacs.json, and info.md. None of the other files ended up needing to move.

hacs-screenshot

### CODE REVIEW

**Comment by alexciesielski** [comment]
Looking forward to getting this merged

**Comment by sampsyo** [comment]
This seems great overall! TBH I don't entirely understand the difference between `info.md` and our `README` we already have… can anyone who uses HACS clarify? In any case, it seems like the actual metadata is ready to go.

**Comment by impankratov** [comment]
@sampsyo regarding `info.md`
>If you want to add a richer experience for your users you can add an info.md file to the root of your repository (this is optional, if you do not have this you need to set render_readme in the hacs.json file), this file will be rendered under the repository description, it does not support the full styling options as Github so use with care

Taken from https://hacs.xyz/docs/publish/start

**Comment by sampsyo** [comment]
OK, merged! That's all we need to do, right? We don't need to enter something into some database somewhere?

**Comment by impankratov** [comment]
@sampsyo 

It could be added to HACS manually (I believe there's an option to import a repo.

But it also could be added to default HACS repository, so it could be available in HACS by default. More info here:  https://hacs.xyz/docs/publish/include

**Comment by javawizard** [comment]
@sampsyo To be clear, you'd need to submit a PR against https://github.com/hacs/default/blob/master/integration adding this repo to the list in order for it to be included. They seem to like maintainers to be the ones to open the PR - is that something you'd have time to do?

**Comment by sampsyo** [comment]
Thanks for clarifying, @javawizard—that seems easy enough! I'll give it a try right now.

**Comment by sampsyo** [comment]
@javawizard I opened a PR but it looks like there's more subtlety to it. If you have time to help shepherd the PR through, we'd be grateful.

**Comment by javawizard** [comment]
@sampsyo Happy to help. What needs to be done? If this is re https://github.com/hacs/default/pull/550#issuecomment-662952965, then per https://github.com/hacs/default/pull/550#issuecomment-662956327 it sounds like that's no longer an issue.

**Comment by sampsyo** [comment]
Indeed! Sounds like that thing's OK. I think the only thing I'm asking for your help with (awesome, thanks for volunteering, by the way) is monitoring the thread to see if there's anything else we need to do. 🙏✨✨

**Comment by javawizard** [comment]
Sure, happy to keep an eye on it 👍

**Comment by KTibow** [comment]
As for brands, you can just duplicate `custom_integrations/smartthinq_sensors` to `custom_integrations/smartthinq`.

**Pull request merged**
